new reusable workflows part of wultra/tasklist#23
wultra/powerauth-push-server pull request #495
Opened 2022-10-14 18:26 UTC by zcgandcomp

2022-10-16 08:37 UTC, romanstrobl requested changes
Unfortunately, this will not work so easily. The `mvn deploy` command in the GitHub action needs to skip tests, because Push Server Maven tests require a running instance of PowerAuth server. See the error in the GitHub actions related to missing `POWERAUTH_ENDPOINT` variable:

```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pushServerTestClientFactory': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'POWERAUTH_ENDPOINT' in value "${POWERAUTH_ENDPOINT}/powerauth-java-server/rest"
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'POWERAUTH_ENDPOINT' in value "${POWERAUTH_ENDPOINT}/powerauth-java-server/rest"
```

2022-10-17 20:27 UTC, romanstrobl commented on .github/workflows/maven-deploy.yml
> +        description:
Missing description.

2022-10-17 20:28 UTC, romanstrobl approved these changes
The workflow will be usable after merging pull request https://github.com/wultra/powerauth-push-server/pull/497.

2022-10-18 09:14 UTC, zcgandcomp commented on .github/workflows/maven-deploy.yml
> +        description:
description added

2022-10-18 09:16 UTC, zcgandcomp commented
rebased on current develop

2022-10-18 09:46 UTC, merged